### ISSUE TITLE
trchat 在啟動階段時會卡loading libraries

### ISSUE THREAD

**Issue by 1636578433** [TrPlugins/TrChat#71]
目前我的伺服器供應商是OVH新加坡
不知道是不是海外的關係好像無法下載libraries
我有嘗試在本機自行建立伺服器運行Trchat,然後把assets和libraries再放入專用伺服器才能順利開啟
但是還是會卡在loading libraries很久

**Comment by 157946a** [comment]
这种原因大概率是网络下载不来,你尝试在别的地段下载,然后复制到你的服务端上

**Comment by 157946a** [comment]
使用最新构建,查看是否还有这个问题
