### ISSUE TITLE
添加 MiniMessage 支持

### ISSUE THREAD

**Issue by YuanYuanOwO** [TrPlugins/TrChat#92]
https://docs.adventure.kyori.net/minimessage/

**Comment by ItsFlicker** [comment]
在聊天中吗

**Comment by YuanYuanOwO** [comment]
> 在聊天中吗

想法是仅聊天可用，配置文件里可用也行

**Comment by YuanYuanOwO** [comment]
> 在聊天中吗

题外话，`/trchat spy`每次下线就会关闭监听私聊是bug吗  

想法是输入`/trchat spy`时才会关闭监听私聊，不是下线时会关闭监听私聊

**Comment by konsheng** [comment]
MiniMessage也不是什么好东西，他只会让配置更加麻烦，得不到任何的新功能。

**Comment by YuanYuanOwO** [comment]
> MiniMessage也不是什么好东西，他只会让配置更加麻烦，得不到任何的新功能。

最初想法是仅聊天可用的，看开发意愿喽

**Comment by konsheng** [comment]
由原来的

> `&a&l&o&m`

转化成

> `<color:green><b>Server</b></color>`

> `<color:green><b>Server</b></color> <b><color:#ff7700><i><u>Minecraft</u></i></color></b>`

会更加难以理解

**Comment by ghost** [comment]
可以使用MineDown

**Comment by konsheng** [comment]
建议并存

________________________________

**Comment by ghost** [comment]
> 

建议看看MineDown的格式

**Comment by ghost** [comment]
https://github.com/Phoenix616/MineDown

**Comment by ghost** [comment]
个人觉得像 MiniMessage、MineDown 这种聊天格式系统还是挺重要的，可以支持 1.16+ 的 HEX 颜色 (及渐变)
[MineDown](https://github.com/Phoenix616/MineDown) 可以做到共存

**Comment by konsheng** [comment]
一起随缘咯，这段时间应该不会更新
![把你偷走](https://user-images.githubusercontent.com/75506674/179368901-f09c2f22-b122-4069-888e-e943dbaf8ca3.gif)

**Comment by ItsFlicker** [comment]
PRE-7支持在铁砧、告示牌中使用

**Comment by ItsFlicker** [comment]
PRE-7支持在铁砧、告示牌中使用

**Comment by noctiro** [comment]
貌似还是没有添加支持？
